export const AUTH_SET_ERROR = 'AUTH_SET_ERROR';
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
export const AUTH_SET_LOADING = 'AUTH_SET_LOADING';

export const CHAT_INIT = 'CHAT_INIT';
export const CHAT_ADD_MESSAGES = 'CHAT_ADD_MESSAGES';
export const CHAT_VOTE = 'CHAT_VOTE';
export const CHAT_SET_LOADING = 'CHAT_SET_LOADING';
export const CHAT_SEND_MESSAGE = 'CHAT_SEND_MESSAGE';
